### ISSUE TITLE
Crash on a server-end that is using this mod

### ISSUE THREAD

**Issue by Sunconure11** [Seraphaestus/HistoricizedMedicine#10]
https://pastebin.com/MDurUPc6

**Comment by Sunconure11** [comment]
I think I know how to fix this.

https://github.com/Alex-the-666/Ice_and_Fire/commit/ad9a5a3077d9778b2f0a1b1d20f72c7174732246#diff-432534fa7d0662ea011917064e884956

**Comment by Sunconure11** [comment]
Hopefully fixed this in #11

**Comment by majijn** [comment]
im still getting crashes on server end, on singleplayer, it doesnt give me a log
playing in peaceful stopped the crashes, so i was guessing it was the rats doing it but maybe I was wrong.

**Comment by Sunconure11** [comment]
Check the server's crash reports folder.

**Comment by majijn** [comment]
its on singleplayer, so it's the normal logs, right?

**Comment by Sunconure11** [comment]
There's also a crash reports folder in singleplayer.
