### ISSUE TITLE
Aaaand it looks like my fix did not work.

### ISSUE THREAD

**Issue by Sunconure11** [Seraphaestus/HistoricizedMedicine#13]
https://pastebin.com/b00XUe1X

**Comment by Sunconure11** [comment]
I believe I've found the issue. I'll try and push out another fix soon.

**Comment by Sunconure11** [comment]
Issue lies with line 149 in EntityUpdate, as it's calling for a class that only exists on the client-end.

**Comment by Seraphaestus** [comment]
Thank you!

**Comment by Sunconure11** [comment]
I tried my hand at attempting another fix, but I got frustrated and just... gave up.

Sunconure11 - Today at 2:09 PM
hm, can someone show me where i screwed up in trying to send a fix for this mod? im trying to see to fixing it
https://github.com/Seraphaestus/HistoricizedMedicine/issues/13
GitHub
Aaaand it looks like my fix did not work. · Issue #13 · Seraphae...
https://pastebin.com/b00XUe1X

https://github.com/Seraphaestus/HistoricizedMedicine/pull/11
GitHub
(Hopefully) Fixed the server-based crashes by Sunconure11 · Pull ...
Issue appears to be a trivial one, but check this page out for future reference.
https://mcforge.readthedocs.io/en/latest/concepts/sides/

it's something wrong with client/server-ending, that i can tell, but it looks like i was wrong about how to approach it
Zabi94 - Today at 2:11 PM
The problem is in the proxy classes
Sunconure11 - Today at 2:11 PM
figured as much, im going to set up a workspace and send over a proper bugfix
Zabi94 - Today at 2:11 PM
Somewhere in the common proxy you used Particle in a non client only environment
Sunconure11 - Today at 2:23 PM
im looking over the code now and i don't see the usage of particle anywhere in commonproxy
https://pastebin.com/0xhsbLYp
Pastebin
package seraphaestus.historicizedmedicine; import java.io.File;...

Zabi94 - Today at 2:28 PM
 at seraphaestus.historicizedmedicine.CommonProxy.registerEventHandlers(CommonProxy.java:75)
Sunconure11 - Today at 2:33 PM
line 75 there is this, could this somehow be screwy? though im testing one thing
   protected void registerEventHandlers(){
        MinecraftForge.EVENT_BUS.register(new EntityUpdate());
    }
Zabi94 - Today at 2:33 PM
Idk
Sunconure11 - Today at 2:33 PM
ill try and apply siding to that, and see what happens
since that's the screwy line according to the error
Zabi94 - Today at 2:34 PM
What does EntityUpdate contain?
Sunconure11 - Today at 2:35 PM
https://pastebin.com/5J7KdaEX
Pastebin
package seraphaestus.historicizedmedicine.Effect; import java.l...

theres a subscribeevent in there, hmmm
im going to clientside it, and see if it does anything
Zabi94 - Today at 2:38 PM
Line 149
Sunconure11 - Today at 2:39 PM
shit, bounding boxes
Zabi94 - Today at 2:39 PM
There's an invocation to the Minecraft class
It's client only
Also, to a class that extends Particle, again, client only
Sunconure11 - Today at 2:40 PM
alright, ill clientside it, and run it against my server once more, to see what happens
hm, looks like i approached that part wrong, what would be the proper way to clientside what this guy did?
hm
maybe it's just a matter of putting it in the right spot
ill toy around for a bit until i find a working solution
hm, im trying to figure out how to resolve this, to no avail :neutral_face:
Zabi94 - Today at 2:55 PM
See how we did it in Bewitchment, the relevant classes are ParticleF and the proxy method I used to spawn them. See my last commit

**Comment by Seraphaestus** [comment]
Would this work?
```
        			...if(plagueDuration % plagueParticleEveryXTicks == 0) {
        				renderParticles(entity, rnd);
        			}...
    
    @SideOnly(Side.CLIENT)
    private void renderParticles(Entity entity, Random rnd) {
    	AxisAlignedBB box = entity.getEntityBoundingBox();
		Minecraft.getMinecraft().effectRenderer.addEffect(new PlagueEffect(entity.getEntityWorld(), entity.posX + (box.maxX - box.minX) * (rnd.nextFloat() - 0.5f), entity.posY + (box.maxY - box.minY) * (rnd.nextFloat()), entity.posZ + (box.maxZ - box.minZ) * (rnd.nextFloat() - 0.5f), 0.0f, 0.0f, 0.0f));   
    }
```

**Comment by Sunconure11** [comment]
You could try it, I'll be willing to compile builds on my end to test to see if servers with the mod can boot up again.

**Comment by Seraphaestus** [comment]
Thank you ever so much friend, you've been a great help. I'm not sure how to test server side problems myself

**Comment by Sunconure11** [comment]
I'm running into an issue compiling the mod on my end for bugtesting

https://pastebin.com/d34hMmMP

**Comment by Seraphaestus** [comment]
I'll build it on my end and upload to curse!

**Comment by Sunconure11** [comment]
It works. I'll test for bugs relating to the server-end later, if any showed up.
