### ISSUE TITLE
Crash with foam fix

### ISSUE THREAD

**Issue by zEpiixz** [Seraphaestus/HistoricizedMedicine#16]
https://pastebin.com/ncCwvpyn

Crash when im near a village.

**Comment by Sunconure11** [comment]
https://pastebin.com/SMAGjnfr

Can confirm a similar crash. I'll see how I can fix this.

**Comment by Sunconure11** [comment]
Crash is unrelated to foamfix, but structure implementation itself. It is not saving the facing of certain parts anywhere.

**Comment by Sunconure11** [comment]
If you're still on @zEpiixz, I have something you can try out, to see if the issue has been resolved.

https://www.dropbox.com/s/hvzkhwke1mb8i6z/historicizedmedicine-1.3.6.jar?dl=0

I'll release this to curse within the next few days

**Comment by zEpiixz** [comment]
Thank you so much :)
