### ISSUE TITLE
Support needs to be implemented for modded honey + other items

### ISSUE THREAD

**Issue by Sunconure11** [Seraphaestus/HistoricizedMedicine#2]
As many, many mods implement honey, there should be some support in this mod for such things.

The following mods add honey:

Growthcraft (it's making it's way to 1.12, albeit slowly)
Erebus
Harvestcraft
Rustic
Forestry
Biomes O' Plenty
Bewitchment (mod I'm making, not released yet, but it has an apiary and beekeeping)

There are probably a bunch of others, I'd advise looking around.

Modded meats should be added for support, as quite a few mob-adding mods add their own meats.

For the herb mixture, allow various crops from other mods, as well as more flowers, to be used in it.

**Comment by LatentDesire** [comment]
I’ll need to cross reference the herbs in Rustic and their medicinal uses, but that would be helpful. Perhaps adding various herbal poultices, tinctures, and salves.

**Comment by Sunconure11** [comment]
Some of the herbs in Rustic appear to be fictional, FYI. Some are real though.

**Comment by Seraphaestus** [comment]
Added honey and raw meat ore dictionarying from other mobs. Will be looking at rustic compatability another time.

**Comment by Sunconure11** [comment]
@LatentDesire For rustic, check the dev's discord, ask them for some info regarding the various plants, since while some are real, some are fictional, but could still have a real-world basis.

https://discord.gg/guqPagm
