### ISSUE TITLE
Bug involving this mod's villagers + villagers from a few other mods

### ISSUE THREAD

**Issue by Sunconure11** [Seraphaestus/HistoricizedMedicine#3]
https://github.com/TeamTotemic/Totemic/issues/85

I'm noticing something that may be similar with Primitive Mobs as well.

**Comment by Seraphaestus** [comment]
Could you describe in more detail? With the affected villagers, what does it show in WAILA/TOP, what trades do they have, what texture do they have?

Also have you found any of the Historicized Medicine villagers in villages?

**Comment by Seraphaestus** [comment]
Rewrote the entity registry code to use subscribe to the entity event and I got this in the log:
```
[17:00:20] [Server thread/ERROR] [FML]:     historicizedmedicine:plaguedoctor: 0
[17:00:20] [Server thread/ERROR] [FML]:     historicizedmedicine:apothecarian: 38
[17:00:20] [Server thread/ERROR] [FML]:     historicizedmedicine:rat: 39
```
So its possible that the plague doctor was registered with an id of 0 which caused some conflicts? I'm not sure, still new to modding, but seems like there might be some correlation

**Comment by Sunconure11** [comment]
Haven't looked much in villages yet, but I did notice the oddity with a JEI plugin that lets me see villager trades.

https://minecraft.curseforge.com/projects/just-enough-resources-jer

**Comment by Seraphaestus** [comment]
Seems good checking through JER and through summoned villager types; hopefully this means my rewrite fixed it and not just that I'm not reproducing the issue.

**Comment by Sunconure11** [comment]
Issue appears to have been resolved.
