### ISSUE TITLE
Suggestion: Illnesses

### ISSUE THREAD

**Issue by LatentDesire** [Seraphaestus/HistoricizedMedicine#4]
Various minor illnesses, as well as diseases. Some cureable at various stages of medicine. Others not curable at all. 

Ranging from the Common Cold to Cancer. 

(Suggestion for an advancement. If you die of dysentery, you get the advancement “Trailblazer”. This is in reference to Oregon Trail.)

**Comment by Seraphaestus** [comment]
This is a cool idea but I think it's out of scope for my mod. I also want to keep things vanilla-feeling and I feel like this would cross that line a bit.
Thank you for the suggestion though  c:
