### ISSUE TITLE
Suggestion: Organ Transplant/Amputation

### ISSUE THREAD

**Issue by LatentDesire** [Seraphaestus/HistoricizedMedicine#5]
Occasionally an organ may begin to fail, likely due to some illness or disease, and need to be replaced. Amputation of an arm or leg may be required if it becomes gangrenous. 

This should also be compatible with Robotic Parts/ReWIRED. Or perhaps only available when the two mods are played together.

**Comment by Seraphaestus** [comment]
This is a cool idea but I think it's out of scope for my mod. I also want to keep things vanilla-feeling and I feel like this would cross that line a bit.
Thank you for the suggestion though c:
