### ISSUE TITLE
Grat on this this mod and minor fix plz!

### ISSUE THREAD

**Issue by alxcool** [Seraphaestus/HistoricizedMedicine#9]
Thk for your dedication on this mod! I don't think any modders tried this approach on regeneration system in minecraft yet.

Lets create a topic summary
i) minor issue
ii) an approach on plague
iii) config

... I. )
historicizedmedicine-1.1.1
Singleplayer 1.12.2 4G ram allocated for >= 130 mods on forge 2679
I've encountered a minor issue concerning a single recipe. The meat bandage require a item who "for x reason" is made unavailable! My mods doesn't include any "raw meat" as material and or, the item is not listed in JEI. So I guess my first reading for the raw meat bandage was including a "ore:allmeatraw" (note I'l fix this name, with the appropriate one later on!). But now, to complete the recipe, JEI only ask the following
A) Use or, to be inside the medical crafting table
B) include an apropriate knowledge items who is mastered.
C) include 2x minecraft:string
D) (item missing in the middle or minecraft:air)

I've tried to complete the recipe using any rawmeat from vanilla but this won't work unfortunately.
However, it is still possible to progress through the story mode without the raw meat bandage. I'm just sad having such nice item suggestion not working.

... II. )

On my first trial in this mod, Ive contracted not an infection, but a plague on my first contact with a rat. I've killed a rat at a battle range of 4 using bow and arrows, then when I've approach at range 2, just to realise that I've contracted the plague. I was thinking, ok not so bad, what do I need to get rid of it? 2 items only available by villagers who have not spawn yet? So I'v tried to ignore the potion effect. Unfortunately later on when I've visited a village, three villagers out of 6 contracted my plague and 2 of them died all in a sudden.

... III. )

Some personal adaptation to the config file...
a) plague have been disabled and turn impossible to spawn on rats, until I'm confident enough about being able to cure it.
b) Lowered possibility to contract the plague by fighting a rat from 40% to 8%.
c) set false to : disable milk bucket, as the rustic milk bottle is still working. 

Note, when I like a mod I feel about leaving some suggestions...
A) Possibility to transfer knowledge points from a container book to the next one... Just a different approach to reach the same goal.
B) Create a hard or high priced way to cure plague using vanilla items
C) Giving my personal thk to this mod author as I finally was able to include a decent way to cure Poison or wither! This feel great!
D) About rats's IA, suggest to use the same IA than the one for the Enderman, because they are cute and I would enjoy having such possibility to consider them as neutral until I stare at one!

**Comment by Seraphaestus** [comment]
Thank you! The positive feedback is very appreciated.

Currently there is a bug with the villagers not spawning. This does mean that currently there is no way to cure plague which is not very good to say the least. In emergencies you can cheat in the item "Plague Cure" to use on infected.

Regarding B: You can do this with the mod Crafttweaker by creating a new recipe for the Plague Cure.

Regarding D: In the future I would like to allow keeping the rats as pets!

**Comment by Seraphaestus** [comment]
The recipe issue will be fixed in the next update. I switched over to using a different ore dictionary name that is the standard among other mods, but forgot to update the recipe with the new name.

**Comment by alxcool** [comment]
Thk for your fast answer I guess I'm just glad being able to play mods for free so when I find the time, I like to comment a few topic. The recipe is fixed in this new version too!
